/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMinhasCandidaturasRouteImport } from './routes/_authenticated/minhas-candidaturas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedConcursosIndexRouteImport } from './routes/_authenticated/concursos.index'
import { Route as AuthenticatedCandidatesIndexRouteImport } from './routes/_authenticated/candidates.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedConcursosIdRouteImport } from './routes/_authenticated/concursos.$id'
import { Route as AuthenticatedCandidatesNewRouteImport } from './routes/_authenticated/candidates.new'
import { Route as AuthenticatedCandidatesIdRouteImport } from './routes/_authenticated/candidates.$id'
import { Route as AuthenticatedAdminUtilizadoresRouteImport } from './routes/_authenticated/admin.utilizadores'
import { Route as AuthenticatedAdminOcupacoesRouteImport } from './routes/_authenticated/admin.ocupacoes'
import { Route as AuthenticatedAdminLocalidadesRouteImport } from './routes/_authenticated/admin.localidades'
import { Route as AuthenticatedAdminInstituicoesRouteImport } from './routes/_authenticated/admin.instituicoes'
import { Route as AuthenticatedAdminCarreirasRouteImport } from './routes/_authenticated/admin.carreiras'
import { Route as AuthenticatedCandidatesIdIndexRouteImport } from './routes/_authenticated/candidates.$id.index'
import { Route as AuthenticatedAdminConcursosIndexRouteImport } from './routes/_authenticated/admin.concursos.index'
import { Route as AuthenticatedCandidatesIdResumeRouteImport } from './routes/_authenticated/candidates.$id.resume'
import { Route as AuthenticatedAdminConcursosNovoRouteImport } from './routes/_authenticated/admin.concursos.novo'
import { Route as AuthenticatedAdminConcursosIdRouteImport } from './routes/_authenticated/admin.concursos.$id'
import { Route as AuthenticatedAdminPrintConcursoIdRouteImport } from './routes/_authenticated/admin.print.concurso.$id'
import { Route as AuthenticatedAdminPrintAprovadosIdRouteImport } from './routes/_authenticated/admin.print.aprovados.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMinhasCandidaturasRoute =
  AuthenticatedMinhasCandidaturasRouteImport.update({
    id: '/minhas-candidaturas',
    path: '/minhas-candidaturas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConcursosIndexRoute =
  AuthenticatedConcursosIndexRouteImport.update({
    id: '/concursos/',
    path: '/concursos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCandidatesIndexRoute =
  AuthenticatedCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedConcursosIdRoute =
  AuthenticatedConcursosIdRouteImport.update({
    id: '/concursos/$id',
    path: '/concursos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCandidatesNewRoute =
  AuthenticatedCandidatesNewRouteImport.update({
    id: '/candidates/new',
    path: '/candidates/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCandidatesIdRoute =
  AuthenticatedCandidatesIdRouteImport.update({
    id: '/candidates/$id',
    path: '/candidates/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUtilizadoresRoute =
  AuthenticatedAdminUtilizadoresRouteImport.update({
    id: '/utilizadores',
    path: '/utilizadores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOcupacoesRoute =
  AuthenticatedAdminOcupacoesRouteImport.update({
    id: '/ocupacoes',
    path: '/ocupacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLocalidadesRoute =
  AuthenticatedAdminLocalidadesRouteImport.update({
    id: '/localidades',
    path: '/localidades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInstituicoesRoute =
  AuthenticatedAdminInstituicoesRouteImport.update({
    id: '/instituicoes',
    path: '/instituicoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCarreirasRoute =
  AuthenticatedAdminCarreirasRouteImport.update({
    id: '/carreiras',
    path: '/carreiras',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCandidatesIdIndexRoute =
  AuthenticatedCandidatesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidatesIdRoute,
  } as any)
const AuthenticatedAdminConcursosIndexRoute =
  AuthenticatedAdminConcursosIndexRouteImport.update({
    id: '/concursos/',
    path: '/concursos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCandidatesIdResumeRoute =
  AuthenticatedCandidatesIdResumeRouteImport.update({
    id: '/resume',
    path: '/resume',
    getParentRoute: () => AuthenticatedCandidatesIdRoute,
  } as any)
const AuthenticatedAdminConcursosNovoRoute =
  AuthenticatedAdminConcursosNovoRouteImport.update({
    id: '/concursos/novo',
    path: '/concursos/novo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConcursosIdRoute =
  AuthenticatedAdminConcursosIdRouteImport.update({
    id: '/concursos/$id',
    path: '/concursos/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPrintConcursoIdRoute =
  AuthenticatedAdminPrintConcursoIdRouteImport.update({
    id: '/print/concurso/$id',
    path: '/print/concurso/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPrintAprovadosIdRoute =
  AuthenticatedAdminPrintAprovadosIdRouteImport.update({
    id: '/print/aprovados/$id',
    path: '/print/aprovados/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/minhas-candidaturas': typeof AuthenticatedMinhasCandidaturasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/carreiras': typeof AuthenticatedAdminCarreirasRoute
  '/admin/instituicoes': typeof AuthenticatedAdminInstituicoesRoute
  '/admin/localidades': typeof AuthenticatedAdminLocalidadesRoute
  '/admin/ocupacoes': typeof AuthenticatedAdminOcupacoesRoute
  '/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRouteWithChildren
  '/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/concursos/$id': typeof AuthenticatedConcursosIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/candidates/': typeof AuthenticatedCandidatesIndexRoute
  '/concursos/': typeof AuthenticatedConcursosIndexRoute
  '/admin/concursos/$id': typeof AuthenticatedAdminConcursosIdRoute
  '/admin/concursos/novo': typeof AuthenticatedAdminConcursosNovoRoute
  '/candidates/$id/resume': typeof AuthenticatedCandidatesIdResumeRoute
  '/admin/concursos/': typeof AuthenticatedAdminConcursosIndexRoute
  '/candidates/$id/': typeof AuthenticatedCandidatesIdIndexRoute
  '/admin/print/aprovados/$id': typeof AuthenticatedAdminPrintAprovadosIdRoute
  '/admin/print/concurso/$id': typeof AuthenticatedAdminPrintConcursoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/minhas-candidaturas': typeof AuthenticatedMinhasCandidaturasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/carreiras': typeof AuthenticatedAdminCarreirasRoute
  '/admin/instituicoes': typeof AuthenticatedAdminInstituicoesRoute
  '/admin/localidades': typeof AuthenticatedAdminLocalidadesRoute
  '/admin/ocupacoes': typeof AuthenticatedAdminOcupacoesRoute
  '/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/concursos/$id': typeof AuthenticatedConcursosIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/candidates': typeof AuthenticatedCandidatesIndexRoute
  '/concursos': typeof AuthenticatedConcursosIndexRoute
  '/admin/concursos/$id': typeof AuthenticatedAdminConcursosIdRoute
  '/admin/concursos/novo': typeof AuthenticatedAdminConcursosNovoRoute
  '/candidates/$id/resume': typeof AuthenticatedCandidatesIdResumeRoute
  '/admin/concursos': typeof AuthenticatedAdminConcursosIndexRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdIndexRoute
  '/admin/print/aprovados/$id': typeof AuthenticatedAdminPrintAprovadosIdRoute
  '/admin/print/concurso/$id': typeof AuthenticatedAdminPrintConcursoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/minhas-candidaturas': typeof AuthenticatedMinhasCandidaturasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/admin/carreiras': typeof AuthenticatedAdminCarreirasRoute
  '/_authenticated/admin/instituicoes': typeof AuthenticatedAdminInstituicoesRoute
  '/_authenticated/admin/localidades': typeof AuthenticatedAdminLocalidadesRoute
  '/_authenticated/admin/ocupacoes': typeof AuthenticatedAdminOcupacoesRoute
  '/_authenticated/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/_authenticated/candidates/$id': typeof AuthenticatedCandidatesIdRouteWithChildren
  '/_authenticated/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/_authenticated/concursos/$id': typeof AuthenticatedConcursosIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/candidates/': typeof AuthenticatedCandidatesIndexRoute
  '/_authenticated/concursos/': typeof AuthenticatedConcursosIndexRoute
  '/_authenticated/admin/concursos/$id': typeof AuthenticatedAdminConcursosIdRoute
  '/_authenticated/admin/concursos/novo': typeof AuthenticatedAdminConcursosNovoRoute
  '/_authenticated/candidates/$id/resume': typeof AuthenticatedCandidatesIdResumeRoute
  '/_authenticated/admin/concursos/': typeof AuthenticatedAdminConcursosIndexRoute
  '/_authenticated/candidates/$id/': typeof AuthenticatedCandidatesIdIndexRoute
  '/_authenticated/admin/print/aprovados/$id': typeof AuthenticatedAdminPrintAprovadosIdRoute
  '/_authenticated/admin/print/concurso/$id': typeof AuthenticatedAdminPrintConcursoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/minhas-candidaturas'
    | '/perfil'
    | '/admin/carreiras'
    | '/admin/instituicoes'
    | '/admin/localidades'
    | '/admin/ocupacoes'
    | '/admin/utilizadores'
    | '/candidates/$id'
    | '/candidates/new'
    | '/concursos/$id'
    | '/admin/'
    | '/candidates/'
    | '/concursos/'
    | '/admin/concursos/$id'
    | '/admin/concursos/novo'
    | '/candidates/$id/resume'
    | '/admin/concursos/'
    | '/candidates/$id/'
    | '/admin/print/aprovados/$id'
    | '/admin/print/concurso/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/minhas-candidaturas'
    | '/perfil'
    | '/admin/carreiras'
    | '/admin/instituicoes'
    | '/admin/localidades'
    | '/admin/ocupacoes'
    | '/admin/utilizadores'
    | '/candidates/new'
    | '/concursos/$id'
    | '/admin'
    | '/candidates'
    | '/concursos'
    | '/admin/concursos/$id'
    | '/admin/concursos/novo'
    | '/candidates/$id/resume'
    | '/admin/concursos'
    | '/candidates/$id'
    | '/admin/print/aprovados/$id'
    | '/admin/print/concurso/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/minhas-candidaturas'
    | '/_authenticated/perfil'
    | '/_authenticated/admin/carreiras'
    | '/_authenticated/admin/instituicoes'
    | '/_authenticated/admin/localidades'
    | '/_authenticated/admin/ocupacoes'
    | '/_authenticated/admin/utilizadores'
    | '/_authenticated/candidates/$id'
    | '/_authenticated/candidates/new'
    | '/_authenticated/concursos/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/candidates/'
    | '/_authenticated/concursos/'
    | '/_authenticated/admin/concursos/$id'
    | '/_authenticated/admin/concursos/novo'
    | '/_authenticated/candidates/$id/resume'
    | '/_authenticated/admin/concursos/'
    | '/_authenticated/candidates/$id/'
    | '/_authenticated/admin/print/aprovados/$id'
    | '/_authenticated/admin/print/concurso/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minhas-candidaturas': {
      id: '/_authenticated/minhas-candidaturas'
      path: '/minhas-candidaturas'
      fullPath: '/minhas-candidaturas'
      preLoaderRoute: typeof AuthenticatedMinhasCandidaturasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/concursos/': {
      id: '/_authenticated/concursos/'
      path: '/concursos'
      fullPath: '/concursos/'
      preLoaderRoute: typeof AuthenticatedConcursosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidates/': {
      id: '/_authenticated/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AuthenticatedCandidatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/concursos/$id': {
      id: '/_authenticated/concursos/$id'
      path: '/concursos/$id'
      fullPath: '/concursos/$id'
      preLoaderRoute: typeof AuthenticatedConcursosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidates/new': {
      id: '/_authenticated/candidates/new'
      path: '/candidates/new'
      fullPath: '/candidates/new'
      preLoaderRoute: typeof AuthenticatedCandidatesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidates/$id': {
      id: '/_authenticated/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AuthenticatedCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/utilizadores': {
      id: '/_authenticated/admin/utilizadores'
      path: '/utilizadores'
      fullPath: '/admin/utilizadores'
      preLoaderRoute: typeof AuthenticatedAdminUtilizadoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ocupacoes': {
      id: '/_authenticated/admin/ocupacoes'
      path: '/ocupacoes'
      fullPath: '/admin/ocupacoes'
      preLoaderRoute: typeof AuthenticatedAdminOcupacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/localidades': {
      id: '/_authenticated/admin/localidades'
      path: '/localidades'
      fullPath: '/admin/localidades'
      preLoaderRoute: typeof AuthenticatedAdminLocalidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/instituicoes': {
      id: '/_authenticated/admin/instituicoes'
      path: '/instituicoes'
      fullPath: '/admin/instituicoes'
      preLoaderRoute: typeof AuthenticatedAdminInstituicoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/carreiras': {
      id: '/_authenticated/admin/carreiras'
      path: '/carreiras'
      fullPath: '/admin/carreiras'
      preLoaderRoute: typeof AuthenticatedAdminCarreirasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/candidates/$id/': {
      id: '/_authenticated/candidates/$id/'
      path: '/'
      fullPath: '/candidates/$id/'
      preLoaderRoute: typeof AuthenticatedCandidatesIdIndexRouteImport
      parentRoute: typeof AuthenticatedCandidatesIdRoute
    }
    '/_authenticated/admin/concursos/': {
      id: '/_authenticated/admin/concursos/'
      path: '/concursos'
      fullPath: '/admin/concursos/'
      preLoaderRoute: typeof AuthenticatedAdminConcursosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/candidates/$id/resume': {
      id: '/_authenticated/candidates/$id/resume'
      path: '/resume'
      fullPath: '/candidates/$id/resume'
      preLoaderRoute: typeof AuthenticatedCandidatesIdResumeRouteImport
      parentRoute: typeof AuthenticatedCandidatesIdRoute
    }
    '/_authenticated/admin/concursos/novo': {
      id: '/_authenticated/admin/concursos/novo'
      path: '/concursos/novo'
      fullPath: '/admin/concursos/novo'
      preLoaderRoute: typeof AuthenticatedAdminConcursosNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/concursos/$id': {
      id: '/_authenticated/admin/concursos/$id'
      path: '/concursos/$id'
      fullPath: '/admin/concursos/$id'
      preLoaderRoute: typeof AuthenticatedAdminConcursosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/print/concurso/$id': {
      id: '/_authenticated/admin/print/concurso/$id'
      path: '/print/concurso/$id'
      fullPath: '/admin/print/concurso/$id'
      preLoaderRoute: typeof AuthenticatedAdminPrintConcursoIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/print/aprovados/$id': {
      id: '/_authenticated/admin/print/aprovados/$id'
      path: '/print/aprovados/$id'
      fullPath: '/admin/print/aprovados/$id'
      preLoaderRoute: typeof AuthenticatedAdminPrintAprovadosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCarreirasRoute: typeof AuthenticatedAdminCarreirasRoute
  AuthenticatedAdminInstituicoesRoute: typeof AuthenticatedAdminInstituicoesRoute
  AuthenticatedAdminLocalidadesRoute: typeof AuthenticatedAdminLocalidadesRoute
  AuthenticatedAdminOcupacoesRoute: typeof AuthenticatedAdminOcupacoesRoute
  AuthenticatedAdminUtilizadoresRoute: typeof AuthenticatedAdminUtilizadoresRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminConcursosIdRoute: typeof AuthenticatedAdminConcursosIdRoute
  AuthenticatedAdminConcursosNovoRoute: typeof AuthenticatedAdminConcursosNovoRoute
  AuthenticatedAdminConcursosIndexRoute: typeof AuthenticatedAdminConcursosIndexRoute
  AuthenticatedAdminPrintAprovadosIdRoute: typeof AuthenticatedAdminPrintAprovadosIdRoute
  AuthenticatedAdminPrintConcursoIdRoute: typeof AuthenticatedAdminPrintConcursoIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCarreirasRoute: AuthenticatedAdminCarreirasRoute,
  AuthenticatedAdminInstituicoesRoute: AuthenticatedAdminInstituicoesRoute,
  AuthenticatedAdminLocalidadesRoute: AuthenticatedAdminLocalidadesRoute,
  AuthenticatedAdminOcupacoesRoute: AuthenticatedAdminOcupacoesRoute,
  AuthenticatedAdminUtilizadoresRoute: AuthenticatedAdminUtilizadoresRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminConcursosIdRoute: AuthenticatedAdminConcursosIdRoute,
  AuthenticatedAdminConcursosNovoRoute: AuthenticatedAdminConcursosNovoRoute,
  AuthenticatedAdminConcursosIndexRoute: AuthenticatedAdminConcursosIndexRoute,
  AuthenticatedAdminPrintAprovadosIdRoute:
    AuthenticatedAdminPrintAprovadosIdRoute,
  AuthenticatedAdminPrintConcursoIdRoute:
    AuthenticatedAdminPrintConcursoIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCandidatesIdRouteChildren {
  AuthenticatedCandidatesIdResumeRoute: typeof AuthenticatedCandidatesIdResumeRoute
  AuthenticatedCandidatesIdIndexRoute: typeof AuthenticatedCandidatesIdIndexRoute
}

const AuthenticatedCandidatesIdRouteChildren: AuthenticatedCandidatesIdRouteChildren =
  {
    AuthenticatedCandidatesIdResumeRoute: AuthenticatedCandidatesIdResumeRoute,
    AuthenticatedCandidatesIdIndexRoute: AuthenticatedCandidatesIdIndexRoute,
  }

const AuthenticatedCandidatesIdRouteWithChildren =
  AuthenticatedCandidatesIdRoute._addFileChildren(
    AuthenticatedCandidatesIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMinhasCandidaturasRoute: typeof AuthenticatedMinhasCandidaturasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedCandidatesIdRoute: typeof AuthenticatedCandidatesIdRouteWithChildren
  AuthenticatedCandidatesNewRoute: typeof AuthenticatedCandidatesNewRoute
  AuthenticatedConcursosIdRoute: typeof AuthenticatedConcursosIdRoute
  AuthenticatedCandidatesIndexRoute: typeof AuthenticatedCandidatesIndexRoute
  AuthenticatedConcursosIndexRoute: typeof AuthenticatedConcursosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMinhasCandidaturasRoute: AuthenticatedMinhasCandidaturasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedCandidatesIdRoute: AuthenticatedCandidatesIdRouteWithChildren,
  AuthenticatedCandidatesNewRoute: AuthenticatedCandidatesNewRoute,
  AuthenticatedConcursosIdRoute: AuthenticatedConcursosIdRoute,
  AuthenticatedCandidatesIndexRoute: AuthenticatedCandidatesIndexRoute,
  AuthenticatedConcursosIndexRoute: AuthenticatedConcursosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
